# Simple RNN 

In [1]:
# Import necessary libraries
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense, Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer

## Step 1: Prepare some toy text data

In [2]:
# Sample text data
texts = [
    'I love machine learning',
    'Deep learning is amazing',
    'RNN is a type of neural network',
    'Neural networks learn patterns in data',
    'I enjoy coding in Python'
]

# Tokenize the text
tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)
sequences = tokenizer.texts_to_sequences(texts)

print('Word Index:', tokenizer.word_index)
print('Sequences:', sequences)

Word Index: {'i': 1, 'learning': 2, 'is': 3, 'neural': 4, 'in': 5, 'love': 6, 'machine': 7, 'deep': 8, 'amazing': 9, 'rnn': 10, 'a': 11, 'type': 12, 'of': 13, 'network': 14, 'networks': 15, 'learn': 16, 'patterns': 17, 'data': 18, 'enjoy': 19, 'coding': 20, 'python': 21}
Sequences: [[1, 6, 7, 2], [8, 2, 3, 9], [10, 3, 11, 12, 13, 4, 14], [4, 15, 16, 17, 5, 18], [1, 19, 20, 5, 21]]


## Step 2: Pad sequences to have the same length

In [3]:
X = pad_sequences(sequences, padding='post')
print('Padded Sequences:\n', X)

Padded Sequences:
 [[ 1  6  7  2  0  0  0]
 [ 8  2  3  9  0  0  0]
 [10  3 11 12 13  4 14]
 [ 4 15 16 17  5 18  0]
 [ 1 19 20  5 21  0  0]]


## Step 3: Build a simple RNN model

In [4]:
vocab_size = len(tokenizer.word_index) + 1

model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=8, input_length=X.shape[1]),
    SimpleRNN(16, activation='tanh'),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 7, 8)              176       
                                                                 
 simple_rnn (SimpleRNN)      (None, 16)                400       
                                                                 
 dense (Dense)               (None, 1)                 17        
                                                                 
Total params: 593
Trainable params: 593
Non-trainable params: 0
_________________________________________________________________


## Step 4: Dummy labels (just for demonstration)

In [5]:
# Creating random binary labels for demo purpose
y = np.array([1, 0, 1, 0, 1])
print('Labels:', y)

Labels: [1 0 1 0 1]


## Step 5: Train the model

In [6]:
history = model.fit(X, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 1s 1s/step - loss: 0.7058 - accuracy: 0.2000
Epoch 2/10
1/1 [==============================] - 0s 6ms/step - loss: 0.6966 - accuracy: 0.4000
Epoch 3/10
1/1 [==============================] - 0s 7ms/step - loss: 0.6875 - accuracy: 0.8000
Epoch 4/10
1/1 [==============================] - 0s 7ms/step - loss: 0.6785 - accuracy: 0.8000
Epoch 5/10
1/1 [==============================] - 0s 6ms/step - loss: 0.6695 - accuracy: 0.8000
Epoch 6/10
1/1 [==============================] - 0s 7ms/step - loss: 0.6605 - accuracy: 0.8000
Epoch 7/10
1/1 [==============================] - 0s 8ms/step - loss: 0.6515 - accuracy: 0.8000
Epoch 8/10
1/1 [==============================] - 0s 7ms/step - loss: 0.6424 - accuracy: 0.8000
Epoch 9/10
1/1 [==============================] - 0s 7ms/step - loss: 0.6332 - accuracy: 0.8000
Epoch 10/10
1/1 [==============================] - 0s 6ms/step - loss: 0.6239 - accuracy: 0.8000
